### ISSUE TITLE
No module named fabtools.deb

### ISSUE THREAD

**Issue by Yenthe666** [ingadhoc/odoo-infrastructure#9]
Hi guys

First error I ran into with a copy from the code of today when I try to install the modules:
<img src="http://i.imgur.com/bl1aZZA.png" alt="Error screen" />

When I do pip checks on both fabric and erppeek they are both there:
<img src="http://i.imgur.com/pqxwI6k.png" alt="Dependencies" />

Am I missing something or?

**Comment by jjscarafia** [comment]
wow, that's strange... don't knwo how to help :(...
Are you running odoo in a virtualenv? have you install this dependencies in that env?
Try to make this imports in python console and see what you get.

**Comment by Yenthe666** [comment]
@jjscarafia my Odoo is running on a virtualized Ubuntu 14.04 (which runs on VMware player)
I've installed both erppeek and fabric through the terminal. 
What exactly do you mean by importing through Python console? Do you mean creating a new Python file with the import and execute that file to test it?

**Comment by Yenthe666** [comment]
@jjscarafia fixed! I did not have the lib fabtools.. Perhaps this should also be included in the https://github.com/ingadhoc/odoo-infrastructure/blob/8.0/requirements.txt file?
It should install fabtools (sudo pip install fabtools) or your module will not work.

**Comment by jjscarafia** [comment]
Closed on issue https://github.com/ingadhoc/odoo-infrastructure/commit/9b8f6e6bc5e654f90d761f673df37115f9810296
Thanks for the suggestion!

**Comment by Yenthe666** [comment]
@jjscarafia looks perfect! And no problem.
